baseURL: https://blog.lekwati.com/
languageCode: en-gb
theme: PaperMod
paginate: 5
title: Shannan's Write-y Things
disqusShortname: shannans-write-y-things
Copyright: |
  &copy; 2020-2021 Shannan Lekwati ([Source](https://github.com/slekwati/blog.lekwati.com))

params:
  comments: true
  ShowReadingTime: true
  homeInfoParams:
      Content: >
        Shannan. 27. Gemini. Likes sunsets and long walks on a beach.

        I'm a qualified Scottish solicitor (lawyer), currently living in Germany, trying to learn the language and complete a university degree in a surprisingly maths heavy course. Of course all this means that I needed a new hobby so I could procrastinate.

        I love reading, writing and cooking, so feel free to reach out about any of the above!
        
        Whilst the majority of my stories are short stories on here, I do have one novel that I am currently workin on. 
